environment               = "staging"
high_availability_enabled = true
db_sku                    = "GP_Standard_D2ds_v4"
vm_sku                    = "Standard_B2s"
web_instance_count        = 2
api_instance_count        = 2
alert_email               = "platform-alerts@example.com"
purge_protection_enabled  = true
log_daily_quota_gb        = 1
# subscription_id         = "<staging-subscription-guid>"  # set for multi-subscription
